# Generated by Django 3.2.6 on 2021-11-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medcyclopedia', '0005_rename_description_drugclass_drugclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugclass',
            name='drugClass',
        ),
    ]
